version: '3.9'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8099:8099"
    depends_on:
      - db
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/WONGSITO?serverTimezone=UTC
      spring.datasource.username: root
      spring.datasource.password: root
      spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect
      spring.sql.init.mode: always
      spring.jpa.hibernate.ddl-auto: create
      server.port: 8090
    networks:
      - mi-red

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: WONGSITO
      MYSQL_ROOT_PASSWORD: root
    hostname: db
    networks:
      - mi-red

networks:
  mi-red:
    driver: bridge
